import type { FileErrorCode } from '../../../../shared/application/error-codes.js';

// HTTP коды принадлежат транспорту; приложение сообщает только причину отказа.
export const fileErrorStatus: Readonly<Record<FileErrorCode, number>> = {
  AUTH_DEPENDENCY_UNAVAILABLE: 503,
  DELETE_DISABLED: 403,
  FILE_DELETING: 409,
  FILE_FORBIDDEN: 403,
  FILE_NOT_FOUND: 404,
  FILE_TOO_LARGE: 413,
  INVALID_FILE_ID: 400,
  INVALID_FILE_NAME: 400,
  INVALID_IMAGE: 415,
  INVALID_PAGINATION: 400,
  INVALID_PROJECT: 400,
  INVALID_VIDEO: 415,
  NOT_FOUND: 404,
  PROJECT_FORBIDDEN: 403,
  STORAGE_INVALID_RESPONSE: 502,
  STORAGE_NOT_CONFIGURED: 503,
  STORAGE_OPERATION_PENDING: 503,
  STORAGE_PROVIDER_MISMATCH: 503,
  STORAGE_UNAVAILABLE: 502,
  UNAUTHORIZED: 401,
  UPLOAD_BUSY: 429,
  VIDEO_PROCESSOR_UNAVAILABLE: 503,
};
